
import { ProductField, FieldType, Category, ProductData, Language } from './types';

export const APP_NAME = "Smart Hub";
export const STORAGE_KEY = "smart_hub_v6_production";
export const DEPLOY_NODE = "PROD-CLOUD-LIVE-01";

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    dashboard: "Dashboard",
    inventory: "Inventory",
    settings: "Field Architect",
    users: "Team Security",
    logout: "Log Out",
    profile_settings: "Profile Protocol",
    authenticated_entity: "Authenticated Entity",
    identifier: "Identifier",
    security_key: "Security Key",
    connection_established: "Establish Connection",
    status_ready: "SKUs Active",
    last_saved: "Last Node Sync",
    all: "Global All",
    no_data: "No Protocol Found",
    category: "Category",
    channel: "Channel",
    brand: "Brand",
    model: "Model/SKU",
    new_entry: "New Entry",
    add_info: "Save Protocol",
    cancel: "Cancel",
    edit: "Modify Node",
    delete: "Purge",
    report_pdf: "Export Analysis",
    reset: "Reset Matrix",
    close: "Terminate Session",
    ai_insights: "AI Market Intelligence",
    generate_insight: "Generate Strategy Report",
    analyzing: "AI Analyzing Global Data...",
    search_placeholder: "Search SKU, Brand, Keywords...",
    ai_analysis_btn: "AI Deep Analysis",
    market_share: "Market Share",
    provision_access: "Provision Member",
    edit_user: "Edit Access Policy",
    clearance: "Clearance Level",
    execute_provision: "Execute Provision",
    save_changes: "Commit Changes",
    delete_confirm: "Permanently purge this record from cloud?",
    price_index: "Price Index",
    monthly_movement: "Monthly Velocity",
    options_config: "Options (Comma Separated)",
    field_name: "Node Identifier",
    field_type: "Data Modality",
    add_node: "Append Node",
    save_node: "Save Node",
    market_intel: "Market Intelligence",
    benchmarking_protocol: "Advanced Functional Benchmarking Protocol",
    global_channels: "Global Channels",
    all_brands: "All Brands",
    ai_tactical_analysis: "AI Tactical Analysis",
    market_penetration: "Market Penetration",
    price_competitiveness: "Price Position",
    segment_volume: "Segment Volume",
    price: "Price",
    sales: "Sales",
    volume: "Volume",
    units: "Units",
    leaderboard: "Market Leaderboard",
    ranking_velocity: "Ranking by Unit Velocity",
    skus_tracked: "SKUs TRACKED",
    market_value: "Market Value",
    velocity: "Velocity",
    expand_waterfall: "EXPAND MARKET WATERFALL",
    ai_lock_hint: "Select Category & Channel for precision AI analysis",
    ai_ready: "AI Node Active: Ready for Analysis",
    full_node_data: "Full Node Intelligence Data",
    visit_link: "Open Source Link",
    price_vs_sales: "Price vs Sales Volume Matrix",
    category_share: "Brand Market Share",
    vs_global_avg: "VS SEGMENT AVG",
    select_architecture: "Select Data Architecture",
    node_definition_mode: "Node Definition Mode",
    field_types: {
      text: "Text Input",
      number: "Numeric Value",
      url: "Web URL",
      image: "Visual Data",
      textarea: "Rich Text",
      rating: "Star Rating",
      select: "Single Selection",
      date: "System Date",
      multi_select_quantity: "Multi-Quantity"
    }
  },
  zh: {
    dashboard: "数据概览",
    inventory: "产品管理",
    settings: "调研架构",
    users: "团队安全",
    logout: "安全退出",
    profile_settings: "个人资料",
    authenticated_entity: "已验证实体",
    identifier: "登录账户",
    security_key: "安全密码",
    connection_established: "建立系统连接",
    status_ready: "条目已就绪",
    last_saved: "同步时间",
    all: "全部显示",
    no_data: "暂无数据条目",
    category: "品类架构",
    channel: "渠道/平台",
    brand: "品牌",
    model: "产品名/型号",
    new_entry: "录入条目",
    add_info: "保存配置",
    cancel: "取消操作",
    edit: "修改节点",
    delete: "永久删除",
    report_pdf: "导出调研报表",
    reset: "重置筛选",
    close: "关闭窗口",
    ai_insights: "AI 市场洞察",
    generate_insight: "生成市场分析策略",
    analyzing: "AI 正在分析全域数据...",
    search_placeholder: "搜索品牌、型号、卖点或差评关键词...",
    ai_analysis_btn: "AI 单品深度分析",
    market_share: "市场份额",
    provision_access: "授权新成员",
    edit_user: "修改成员权限",
    clearance: "权限层级",
    execute_provision: "执行授权",
    save_changes: "保存更改",
    delete_confirm: "确认从云端永久删除此条目？",
    price_index: "价格对标指数",
    monthly_movement: "月度动向",
    options_config: "选项配置 (以逗号分隔)",
    field_name: "字段名称",
    field_type: "数据类型",
    add_node: "添加字段节点",
    save_node: "保存字段",
    market_intel: "市场情报中心",
    benchmarking_protocol: "高级功能基准分析协议",
    global_channels: "全球渠道总览",
    all_brands: "全品牌列表",
    ai_tactical_analysis: "AI 战术分析报告",
    market_penetration: "市场渗透率",
    price_competitiveness: "价格定位指数",
    segment_volume: "细分市场销量",
    price: "价格",
    sales: "销量",
    volume: "销量",
    units: "件",
    leaderboard: "单品销量排行榜",
    ranking_velocity: "基于月度销量的实时排名",
    skus_tracked: "个活跃单品被追踪",
    market_value: "市场价格",
    velocity: "销售动向",
    expand_waterfall: "展开更多市场数据",
    ai_lock_hint: "请先选择具体品类和平台以开启 AI 精准分析",
    ai_ready: "AI 节点就绪：可进行市场深度分析",
    full_node_data: "全量情报节点数据",
    visit_link: "访问原始链接",
    price_vs_sales: "价格与销量关系矩阵",
    category_share: "品牌销量占比分布",
    vs_global_avg: "对比市场细分均价",
    select_architecture: "选择录入的数据架构",
    node_definition_mode: "节点定义编辑模式",
    field_types: {
      text: "短文本录入",
      number: "数值/金额",
      url: "网页链接",
      image: "调研主图",
      textarea: "长文本/多行",
      rating: "星级评分",
      select: "单选下拉框",
      date: "系统日期选择",
      multi_select_quantity: "多选带数量"
    }
  },
  ja: {
    dashboard: "ダッシュボード",
    inventory: "製品管理",
    settings: "調査構成",
    users: "チーム管理",
    logout: "ログアウト",
    profile_settings: "プロファイル設定",
    authenticated_entity: "認証済み",
    identifier: "アカウント",
    security_key: "パスワード",
    connection_established: "接続開始",
    status_ready: "有効データ",
    last_saved: "最終同期",
    all: "すべて表示",
    no_data: "データが見つかりません",
    category: "カテゴリ構成",
    channel: "チャネル/プラットフォーム",
    brand: "ブランド",
    model: "モデル/型番",
    new_entry: "新規登録",
    add_info: "プロトコル保存",
    cancel: "キャンセル",
    edit: "ノード編集",
    delete: "削除",
    report_pdf: "レポート出力",
    reset: "フィルターリセット",
    close: "閉じる",
    ai_insights: "AI戦略インサイト",
    generate_insight: "戦略レポート作成",
    analyzing: "AIがデータを分析中...",
    search_placeholder: "ブランド、型番、キーワードを検索...",
    ai_analysis_btn: "AI詳細分析",
    market_share: "市場シェア",
    provision_access: "メンバー招待",
    edit_user: "権限ポリシー編集",
    clearance: "権限レベル",
    execute_provision: "招待を実行",
    save_changes: "変更を保存",
    delete_confirm: "このデータを完全に削除しますか？",
    price_index: "価格指数",
    monthly_movement: "月間動向",
    options_config: "オプション (カンマ区切り)",
    field_name: "ノード名",
    field_type: "データ形式",
    add_node: "ノード追加",
    save_node: "ノード保存",
    market_intel: "市場インテリジェンス",
    benchmarking_protocol: "高度な機能ベンチマーク",
    global_channels: "グローバルチャネル",
    all_brands: "すべてのブランド",
    ai_tactical_analysis: "AI戦術分析レポート",
    market_penetration: "市場シェア率",
    price_competitiveness: "価格ポジション",
    segment_volume: "セグメント販売数",
    price: "価格",
    sales: "販売数",
    volume: "販売数",
    units: "個",
    leaderboard: "マーケットリーダーボード",
    ranking_velocity: "販売速度によるランキング",
    skus_tracked: "個のSKUを追跡中",
    market_value: "市場価格",
    velocity: "販売動向",
    expand_waterfall: "さらに表示",
    ai_lock_hint: "精密分析のためにカテゴリとチャネルを選択してください",
    ai_ready: "AIノード有効：分析準備完了",
    full_node_data: "フルインテリジェンスデータ",
    visit_link: "リンクを開く",
    price_vs_sales: "価格と販売数のマトリックス",
    category_share: "ブランド別シェア分布",
    vs_global_avg: "セグメント平均との比較",
    select_architecture: "データアーキテクチャの選択",
    node_definition_mode: "ノード定義モード",
    field_types: {
      text: "テキスト入力",
      number: "数値/金額",
      url: "ウェブリンク",
      image: "画像データ",
      textarea: "長文テキスト",
      rating: "評価スコア",
      select: "単一選択",
      date: "カレンダー選択",
      multi_select_quantity: "複数選択（数量付）"
    }
  }
};

// 核心系统默认字段 - 固定字段，不作为动态属性
export const CORE_SYSTEM_FIELDS: ProductField[] = [
  { id: 'brand', name: '品牌', type: FieldType.TEXT, required: true },
  { id: 'model', name: '产品名/型号', type: FieldType.TEXT, required: true },
  { id: 'linkUrl', name: '产品链接', type: FieldType.URL, required: false },
  { id: 'channel', name: '渠道/平台', type: FieldType.SELECT, required: true, options: ['淘宝', '京东', '拼多多', '天猫', '抖音', '快手', '小红书', '其他'] },
  { id: 'price', name: '价格', type: FieldType.NUMBER, required: true },
  { id: 'monthlySales', name: '月销量', type: FieldType.NUMBER, required: false },
  { id: 'rating', name: '评分', type: FieldType.RATING, required: false },
  { id: 'mainImage', name: '主图', type: FieldType.IMAGE, required: false },
];

// 品类特定动态字段 - 仅作为示例，实际会从 category_templates 加载
export const CATEGORY_SPECIFIC_FIELDS: ProductField[] = [
  { id: 'period', name: '记录日期', type: FieldType.DATE, required: true },
  { id: 'dataReliability', name: '数据可信度', type: FieldType.SELECT, required: false, options: ['高 (确凿数据)', '中 (经验估算)', '低 (仅供参考)'] },
  { id: 'sellingPoints', name: '核心卖点 (USP)', type: FieldType.TEXTAREA, required: false },
  { id: 'marketDiff', name: '差异化/空白机会', type: FieldType.TEXTAREA, required: false },
  { id: 'proPoints', name: '好评高频词', type: FieldType.TEXT, required: false },
  { id: 'conPoints', name: '差评高频词', type: FieldType.TEXT, required: false },
  { id: 'targetAudience', name: '场景/人群分析', type: FieldType.TEXT, required: false },
];

// 兼容性：保持原有字段定义，但不再用于新表单
export const BASE_SYSTEM_FIELDS: ProductField[] = [
  { id: 'period', name: '记录日期', type: FieldType.DATE, required: true },
  { id: 'channel', name: '渠道/平台', type: FieldType.SELECT, required: true, options: ['Amazon.co.jp', '楽天市場', 'Yahoo!JP', 'Qoo10', 'Direct', 'B2B'] },
  { id: 'shopName', name: '店铺名', type: FieldType.TEXT, required: false },
  { id: 'brand', name: '品牌', type: FieldType.TEXT, required: true },
  { id: 'model', name: '产品名/型号', type: FieldType.TEXT, required: true },
  { id: 'price', name: '价格(含税)', type: FieldType.NUMBER, required: true },
  { id: 'actualPrice', name: '到手价/券后', type: FieldType.NUMBER, required: false },
  { id: 'monthlySales', name: '月销量线索', type: FieldType.NUMBER, required: true },
  { id: 'rating', name: '评分', type: FieldType.RATING, required: false },
  { id: 'mainImage', name: '调研主图', type: FieldType.IMAGE, required: false },
];

export const RESEARCH_FIELDS: ProductField[] = [
  { id: 'url', name: '产品链接URL', type: FieldType.URL, required: false },
  { id: 'dataReliability', name: '数据可信度', type: FieldType.SELECT, required: false, options: ['高 (确凿数据)', '中 (经验估算)', '低 (仅供参考)'] },
  { id: 'sellingPoints', name: '核心卖点 (USP)', type: FieldType.TEXTAREA, required: false },
  { id: 'marketDiff', name: '差异化/空白机会', type: FieldType.TEXTAREA, required: false },
  { id: 'proPoints', name: '好评高频词', type: FieldType.TEXT, required: false },
  { id: 'conPoints', name: '差评高频词', type: FieldType.TEXT, required: false },
  { id: 'targetAudience', name: '场景/人群分析', type: FieldType.TEXT, required: false },
];

export const INITIAL_FIELDS: ProductField[] = [...BASE_SYSTEM_FIELDS, ...RESEARCH_FIELDS];

const TODAY = new Date().toISOString().split('T')[0];
export const MOCK_PRODUCTS: ProductData[] = [
  { 
    id: 'm1', 
    period: TODAY, 
    categoryId: 'cat_powerbank', 
    channel: 'Amazon.co.jp', 
    brand: 'Anker', 
    model: '737 Power Bank (GaNPrime)', 
    price: 19990, 
    monthlySales: 4500, 
    rating: 4.8, 
    createdAt: Date.now(), 
    mainImage: 'https://picsum.photos/seed/m1/400/500',
    dataReliability: '高 (确凿数据)',
    sellingPoints: '支持PD 3.1 140W双向快充，带智能数显屏。'
  },
];

const POWERBANK_FIELDS: ProductField[] = [
  ...BASE_SYSTEM_FIELDS,
  ...RESEARCH_FIELDS,
  { id: 'capacity_mah', name: '容量 (mAh)', type: FieldType.NUMBER, required: false },
  { id: 'max_output', name: '最大输出 (W)', type: FieldType.NUMBER, required: false },
];

const CHARGER_FIELDS: ProductField[] = [
  ...BASE_SYSTEM_FIELDS,
  ...RESEARCH_FIELDS,
  { id: 'max_power', name: '总功率 (W)', type: FieldType.NUMBER, required: false },
];

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'cat_powerbank', name: '移动电源 (3C)', fields: POWERBANK_FIELDS },
  { id: 'cat_charger', name: '充电器/适配器 (3C)', fields: CHARGER_FIELDS }
];
