
import { ProductField, FieldType, Category, ProductData, Language } from './types';

export const APP_NAME = "Smart Hub";
export const STORAGE_KEY = "smart_hub_v6_production";
export const DEPLOY_NODE = "PROD-CLOUD-LIVE-01";

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    dashboard: "Dashboard",
    inventory: "Inventory",
    settings: "Field Architect",
    users: "Team Security",
    logout: "Log Out",
    profile_settings: "Profile Protocol",
    authenticated_entity: "Authenticated Entity",
    identifier: "Identifier",
    security_key: "Security Key",
    connection_established: "Establish Connection",
    status_ready: "SKUs Active",
    last_saved: "Last Node Sync",
    all: "Global All",
    no_data: "No Protocol Found",
    category: "Category",
    channel: "Channel",
    brand: "Brand",
    model: "Model/SKU",
    new_entry: "New Entry",
    add_info: "Save Protocol",
    cancel: "Cancel",
    edit: "Modify Node",
    delete: "Purge",
    report_pdf: "Export Analysis",
    reset: "Reset Matrix",
    close: "Terminate Session",
    ai_insights: "AI Market Intelligence",
    generate_insight: "Generate Strategy Report",
    analyzing: "AI Analyzing Global Data...",
    search_placeholder: "Search SKU, Brand, Keywords...",
    ai_analysis_btn: "AI Deep Analysis",
    market_share: "Market Share",
    provision_access: "Provision Member",
    edit_user: "Edit Access Policy",
    clearance: "Clearance Level",
    execute_provision: "Execute Provision",
    save_changes: "Commit Changes",
    delete_confirm: "Permanently purge this record from cloud?",
    price_index: "Price Index",
    monthly_movement: "Monthly Velocity",
    options_config: "Options (Comma Separated)",
    field_name: "Node Identifier",
    field_type: "Data Modality",
    add_node: "Append Node",
    save_node: "Save Node",
    market_intel: "Market Intelligence",
    benchmarking_protocol: "Advanced Functional Benchmarking Protocol",
    global_channels: "Global Channels",
    all_brands: "All Brands",
    ai_tactical_analysis: "AI Tactical Analysis",
    market_penetration: "Market Penetration",
    price_competitiveness: "Price Position",
    segment_volume: "Segment Volume",
    price: "Price",
    sales: "Sales",
    volume: "Volume",
    units: "Units",
    leaderboard: "Market Leaderboard",
    ranking_velocity: "Ranking by Unit Velocity",
    skus_tracked: "SKUs TRACKED",
    market_value: "Market Value",
    velocity: "Velocity",
    expand_waterfall: "EXPAND MARKET WATERFALL",
    ai_lock_hint: "Select Category & Channel for precision AI analysis",
    ai_ready: "AI Node Active: Ready for Analysis",
    full_node_data: "Full Node Intelligence Data",
    visit_link: "Open Source Link",
    price_vs_sales: "Price vs Sales Volume Matrix",
    category_share: "Brand Market Share",
    vs_global_avg: "VS SEGMENT AVG",
    select_architecture: "Select Data Architecture",
    node_definition_mode: "Node Definition Mode",
    syncing: "Syncing",
    cloud_active: "Cloud Active",
    field_types: {
      text: "Text Input",
      number: "Numeric Value",
      url: "Web URL",
      image: "Visual Data",
      textarea: "Rich Text",
      rating: "Star Rating",
      select: "Single Selection",
      date: "System Date",
      multi_select_quantity: "Multi-Quantity"
    }
  },
  zh: {
    dashboard: "数据概览",
    inventory: "产品管理",
    settings: "调研架构",
    users: "团队安全",
    logout: "安全退出",
    profile_settings: "个人资料",
    authenticated_entity: "已验证实体",
    identifier: "登录账户",
    security_key: "安全密码",
    connection_established: "建立系统连接",
    status_ready: "条目已就绪",
    last_saved: "同步时间",
    all: "全部显示",
    no_data: "暂无数据条目",
    category: "品类架构",
    channel: "渠道/平台",
    brand: "品牌",
    model: "产品名/型号",
    new_entry: "录入条目",
    add_info: "保存配置",
    cancel: "取消操作",
    edit: "修改节点",
    delete: "永久删除",
    report_pdf: "导出调研报表",
    reset: "重置筛选",
    close: "关闭窗口",
    ai_insights: "AI 市场洞察",
    generate_insight: "生成市场分析策略",
    analyzing: "AI 正在分析全域数据...",
    search_placeholder: "搜索品牌、型号、卖点或差评关键词...",
    ai_analysis_btn: "AI 单品深度分析",
    market_share: "市场份额",
    provision_access: "授权新成员",
    edit_user: "修改成员权限",
    clearance: "权限层级",
    execute_provision: "执行授权",
    save_changes: "保存更改",
    delete_confirm: "确认从云端永久删除此条目？",
    price_index: "价格对标指数",
    monthly_movement: "月度动向",
    options_config: "选项配置 (以逗号分隔)",
    field_name: "字段名称",
    field_type: "数据类型",
    add_node: "添加字段节点",
    save_node: "保存字段",
    market_intel: "市场情报中心",
    benchmarking_protocol: "高级功能基准分析协议",
    global_channels: "全球渠道总览",
    all_brands: "全品牌列表",
    ai_tactical_analysis: "AI 战术分析报告",
    market_penetration: "市场渗透率",
    price_competitiveness: "价格定位指数",
    segment_volume: "细分市场销量",
    price: "价格",
    sales: "销量",
    volume: "销量",
    units: "件",
    leaderboard: "单品销量排行榜",
    ranking_velocity: "基于月度销量的实时排名",
    skus_tracked: "个活跃单品被追踪",
    market_value: "市场价格",
    velocity: "销售动向",
    expand_waterfall: "展开更多市场数据",
    ai_lock_hint: "请先选择具体品类和平台以开启 AI 精准分析",
    ai_ready: "AI 节点就绪：可进行市场深度分析",
    full_node_data: "全量情报节点数据",
    visit_link: "访问原始链接",
    price_vs_sales: "价格与销量关系矩阵",
    category_share: "品牌销量占比分布",
    vs_global_avg: "对比市场细分均价",
    select_architecture: "选择录入的数据架构",
    node_definition_mode: "节点定义编辑模式",
    syncing: "同步中",
    cloud_active: "云端在线",
    field_types: {
      text: "短文本录入",
      number: "数值/金额",
      url: "网页链接",
      image: "调研主图",
      textarea: "长文本/多行",
      rating: "星级评分",
      select: "单选下拉框",
      date: "系统日期选择",
      multi_select_quantity: "多选带数量"
    }
  },
  ja: {
    dashboard: "ダッシュボード",
    inventory: "製品管理",
    settings: "調査構成",
    users: "チーム管理",
    logout: "ログアウト",
    profile_settings: "プロファイル設定",
    authenticated_entity: "認証済み",
    identifier: "アカウント",
    security_key: "パスワード",
    connection_established: "接続開始",
    status_ready: "有効データ",
    last_saved: "最終同期",
    all: "すべて表示",
    no_data: "データが見つかりません",
    category: "カテゴリ構成",
    channel: "チャネル/プラットフォーム",
    brand: "ブランド",
    model: "モデル/型番",
    new_entry: "新規登録",
    add_info: "プロトコル保存",
    cancel: "キャンセル",
    edit: "ノード編集",
    delete: "削除",
    report_pdf: "レポート出力",
    reset: "フィルターリセット",
    close: "閉じる",
    ai_insights: "AI戦略インサイト",
    generate_insight: "戦略レポート作成",
    analyzing: "AIがデータを分析中...",
    search_placeholder: "ブランド、型番、キーワードを検索...",
    ai_analysis_btn: "AI詳細分析",
    market_share: "市場シェア",
    provision_access: "メンバー招待",
    edit_user: "権限ポリシー編集",
    clearance: "権限レベル",
    execute_provision: "招待を実行",
    save_changes: "変更を保存",
    delete_confirm: "このデータを完全に削除しますか？",
    price_index: "価格指数",
    monthly_movement: "月間動向",
    options_config: "オプション (カンマ区切り)",
    field_name: "ノード名",
    field_type: "データ形式",
    add_node: "ノード追加",
    save_node: "ノード保存",
    market_intel: "市場インテリジェンス",
    benchmarking_protocol: "高度な機能ベンチマーク",
    global_channels: "グローバルチャネル",
    all_brands: "すべてのブランド",
    ai_tactical_analysis: "AI戦術分析レポート",
    market_penetration: "市場シェア率",
    price_competitiveness: "価格ポジション",
    segment_volume: "セグメント販売数",
    price: "価格",
    sales: "販売数",
    volume: "販売数",
    units: "個",
    leaderboard: "マーケットリーダーボード",
    ranking_velocity: "販売速度によるランキング",
    skus_tracked: "個のSKUを追跡中",
    market_value: "市場価格",
    velocity: "販売動向",
    expand_waterfall: "さらに表示",
    ai_lock_hint: "精密分析のためにカテゴリとチャネルを選択してください",
    ai_ready: "AIノード有効：分析準備完了",
    full_node_data: "フルインテリジェンスデータ",
    visit_link: "リンクを開く",
    price_vs_sales: "価格と販売数のマトリックス",
    category_share: "ブランド別シェア分布",
    vs_global_avg: "セグメント平均との比較",
    select_architecture: "データアーキテクチャの選択",
    node_definition_mode: "ノード定義モード",
    syncing: "同期中",
    cloud_active: "クラウド接続",
    field_types: {
      text: "テキスト入力",
      number: "数値/金額",
      url: "ウェブリンク",
      image: "画像データ",
      textarea: "長文テキスト",
      rating: "評価スコア",
      select: "単一選択",
      date: "カレンダー選択",
      multi_select_quantity: "複数選択（数量付）"
    }
  }
};

// 核心系统默认字段 - 固定字段，不作为动态属性
export const CORE_SYSTEM_FIELDS: ProductField[] = [
  { id: 'brand', name: '品牌', type: FieldType.TEXT, required: true },
  { id: 'model', name: '产品名/型号', type: FieldType.TEXT, required: true },
  { id: 'linkUrl', name: '产品链接', type: FieldType.URL, required: false },
  { id: 'channel', name: '渠道/平台', type: FieldType.SELECT, required: true, options: ['Amazon', 'Rakuten', 'Yahoo Shopping'] },
  { id: 'shopName', name: '店铺名', type: FieldType.TEXT, required: false },
  { id: 'price', name: '价格', type: FieldType.NUMBER, required: true },
  { id: 'monthlySales', name: '月销量', type: FieldType.NUMBER, required: false },
  { id: 'rating', name: '评分', type: FieldType.RATING, required: false },
  { id: 'mainImage', name: '主图', type: FieldType.IMAGE, required: false },
];

// 品类特定动态字段 - 仅作为示例，实际会从 category_templates 加载
export const CATEGORY_SPECIFIC_FIELDS: ProductField[] = [
  { id: 'period', name: '记录日期', type: FieldType.DATE, required: true },
  { id: 'dataReliability', name: '数据可信度', type: FieldType.SELECT, required: false, options: ['高 (确凿数据)', '中 (经验估算)', '低 (仅供参考)'] },
  { id: 'sellingPoints', name: '核心卖点 (USP)', type: FieldType.TEXTAREA, required: false },
  { id: 'marketDiff', name: '差异化/空白机会', type: FieldType.TEXTAREA, required: false },
  { id: 'proPoints', name: '好评高频词', type: FieldType.TEXT, required: false },
  { id: 'conPoints', name: '差评高频词', type: FieldType.TEXT, required: false },
  { id: 'targetAudience', name: '场景/人群分析', type: FieldType.TEXT, required: false },
];

// 兼容性：保持原有字段定义，但不再用于新表单
export const BASE_SYSTEM_FIELDS: ProductField[] = [
  { id: 'period', name: '记录日期', type: FieldType.DATE, required: true },
  { id: 'channel', name: '渠道/平台', type: FieldType.SELECT, required: true, options: ['Amazon', 'Rakuten', 'Yahoo Shopping'] },
  { id: 'shopName', name: '店铺名', type: FieldType.TEXT, required: false },
  { id: 'brand', name: '品牌', type: FieldType.TEXT, required: true },
  { id: 'model', name: '产品名/型号', type: FieldType.TEXT, required: true },
  { id: 'price', name: '价格(含税)', type: FieldType.NUMBER, required: true },
  { id: 'actualPrice', name: '到手价/券后', type: FieldType.NUMBER, required: false },
  { id: 'monthlySales', name: '月销量线索', type: FieldType.NUMBER, required: true },
  { id: 'rating', name: '评分', type: FieldType.RATING, required: false },
  { id: 'mainImage', name: '调研主图', type: FieldType.IMAGE, required: false },
];

export const RESEARCH_FIELDS: ProductField[] = [
  { id: 'url', name: '产品链接URL', type: FieldType.URL, required: false },
  { id: 'dataReliability', name: '数据可信度', type: FieldType.SELECT, required: false, options: ['高 (确凿数据)', '中 (经验估算)', '低 (仅供参考)'] },
  { id: 'sellingPoints', name: '核心卖点 (USP)', type: FieldType.TEXTAREA, required: false },
  { id: 'marketDiff', name: '差异化/空白机会', type: FieldType.TEXTAREA, required: false },
  { id: 'proPoints', name: '好评高频词', type: FieldType.TEXT, required: false },
  { id: 'conPoints', name: '差评高频词', type: FieldType.TEXT, required: false },
  { id: 'targetAudience', name: '场景/人群分析', type: FieldType.TEXT, required: false },
];

export const INITIAL_FIELDS: ProductField[] = [...BASE_SYSTEM_FIELDS, ...RESEARCH_FIELDS];

const TODAY = new Date().toISOString().split('T')[0];
const NOW = Date.now();

const POWERBANK_FIELDS: ProductField[] = [
  ...BASE_SYSTEM_FIELDS,
  ...RESEARCH_FIELDS,
  { id: 'capacity_mah', name: '容量 (mAh)', type: FieldType.NUMBER, required: false },
  { id: 'max_output', name: '最大输出 (W)', type: FieldType.NUMBER, required: false },
];

const CHARGER_FIELDS: ProductField[] = [
  ...BASE_SYSTEM_FIELDS,
  ...RESEARCH_FIELDS,
  { id: 'max_power', name: '总功率 (W)', type: FieldType.NUMBER, required: false },
];

const EARBUDS_FIELDS: ProductField[] = [
  ...BASE_SYSTEM_FIELDS,
  ...RESEARCH_FIELDS,
  { id: 'battery_life', name: '续航时间(h)', type: FieldType.NUMBER, required: false },
  { id: 'bluetooth_version', name: '蓝牙版本', type: FieldType.SELECT, required: false, options: ['5.0', '5.1', '5.2', '5.3'] },
  { id: 'noise_cancelling', name: '降噪功能', type: FieldType.SELECT, required: false, options: ['主动降噪', '被动降噪', '无'] },
  { id: 'water_resistance', name: '防水等级', type: FieldType.SELECT, required: false, options: ['IPX4', 'IPX5', 'IPX7', 'IP68'] },
];

const SMARTWATCH_FIELDS: ProductField[] = [
  ...BASE_SYSTEM_FIELDS,
  ...RESEARCH_FIELDS,
  { id: 'screen_size', name: '屏幕尺寸(英寸)', type: FieldType.NUMBER, required: false },
  { id: 'compatibility', name: '兼容系统', type: FieldType.TEXT, required: false },
  { id: 'battery_days', name: '续航天数', type: FieldType.NUMBER, required: false },
  { id: 'water_resistance', name: '防水等级', type: FieldType.SELECT, required: false, options: ['30m', '50m', '100m', '200m'] },
];

const LAPTOP_FIELDS: ProductField[] = [
  ...BASE_SYSTEM_FIELDS,
  ...RESEARCH_FIELDS,
  { id: 'cpu_model', name: '处理器型号', type: FieldType.TEXT, required: false },
  { id: 'ram_gb', name: '内存(GB)', type: FieldType.NUMBER, required: false },
  { id: 'storage_gb', name: '存储(GB)', type: FieldType.NUMBER, required: false },
  { id: 'screen_size', name: '屏幕尺寸(英寸)', type: FieldType.NUMBER, required: false },
  { id: 'weight_kg', name: '重量(kg)', type: FieldType.NUMBER, required: false },
];

const PHONE_FIELDS: ProductField[] = [
  ...BASE_SYSTEM_FIELDS,
  ...RESEARCH_FIELDS,
  { id: 'screen_size', name: '屏幕尺寸(英寸)', type: FieldType.NUMBER, required: false },
  { id: 'ram_gb', name: '内存(GB)', type: FieldType.NUMBER, required: false },
  { id: 'storage_gb', name: '存储(GB)', type: FieldType.NUMBER, required: false },
  { id: 'battery_mah', name: '电池容量(mAh)', type: FieldType.NUMBER, required: false },
  { id: 'network_5g', name: '5G网络', type: FieldType.SELECT, required: false, options: ['支持', '不支持'] },
];

export const MOCK_PRODUCTS: ProductData[] = [
  // 移动电源 5 条
  { id: 'm1', period: TODAY, categoryId: 'cat_powerbank', channel: 'Amazon', brand: 'Anker', model: '737 Power Bank (GaNPrime)', price: 199, monthlySales: 4500, rating: 4.8, createdAt: NOW, mainImage: 'https://picsum.photos/seed/m1/400/500', shopName: 'Anker Official', capacity_mah: 24000, max_output: 140, dataReliability: '高 (确凿数据)', sellingPoints: 'PD 3.1 140W双向快充，智能数显屏。' },
  { id: 'm2', period: TODAY, categoryId: 'cat_powerbank', channel: 'Rakuten', brand: '小米', model: '10000mAh 33W 快充版', price: 89, monthlySales: 12000, rating: 4.6, createdAt: NOW - 86400000, mainImage: 'https://picsum.photos/seed/m2/400/500', shopName: '小米旗舰店', capacity_mah: 10000, max_output: 33, sellingPoints: '高性价比，小米生态链。' },
  { id: 'm3', period: TODAY, categoryId: 'cat_powerbank', channel: 'Yahoo Shopping', brand: '罗马仕', model: 'Sense 6+ 20000mAh', price: 129, monthlySales: 8000, rating: 4.5, createdAt: NOW - 172800000, mainImage: 'https://picsum.photos/seed/m3/400/500', shopName: 'Romoss Store', capacity_mah: 20000, max_output: 22, sellingPoints: '大容量，双USB输出。' },
  { id: 'm4', period: TODAY, categoryId: 'cat_powerbank', channel: 'Amazon', brand: '紫米', model: '20号 Pro 25000mAh', price: 369, monthlySales: 3200, rating: 4.9, createdAt: NOW - 259200000, mainImage: 'https://picsum.photos/seed/m4/400/500', shopName: 'ZMI Official', capacity_mah: 25000, max_output: 200, sellingPoints: '专业级，支持笔记本充电。' },
  { id: 'm5', period: TODAY, categoryId: 'cat_powerbank', channel: 'Rakuten', brand: '品胜', model: 'PB-T20 20000mAh', price: 99, monthlySales: 5600, rating: 4.4, createdAt: NOW - 345600000, mainImage: 'https://picsum.photos/seed/m5/400/500', shopName: 'Pisen Direct', capacity_mah: 20000, max_output: 18, sellingPoints: '国民品牌，稳定耐用。' },

  // 充电器 4 条
  { id: 'c1', period: TODAY, categoryId: 'cat_charger', channel: 'Amazon', brand: 'Anker', model: 'GaNPrime 120W 三口', price: 269, monthlySales: 2800, rating: 4.8, createdAt: NOW, mainImage: 'https://picsum.photos/seed/c1/400/500', shopName: 'Anker Official', max_power: 120, sellingPoints: 'GaN氮化镓，三设备同时快充。' },
  { id: 'c2', period: TODAY, categoryId: 'cat_charger', channel: 'Rakuten', brand: '小米', model: '67W 氮化镓套装', price: 149, monthlySales: 6500, rating: 4.7, createdAt: NOW - 86400000, mainImage: 'https://picsum.photos/seed/c2/400/500', shopName: '小米旗舰店', max_power: 67, sellingPoints: '套装含线，性价比高。' },
  { id: 'c3', period: TODAY, categoryId: 'cat_charger', channel: 'Yahoo Shopping', brand: '绿联', model: '100W 四口氮化镓', price: 199, monthlySales: 4200, rating: 4.6, createdAt: NOW - 172800000, mainImage: 'https://picsum.photos/seed/c3/400/500', shopName: 'UGREEN Store', max_power: 100, sellingPoints: '四口输出，多设备办公。' },
  { id: 'c4', period: TODAY, categoryId: 'cat_charger', channel: 'Amazon', brand: 'Baseus', model: '65W 氮化镓', price: 89, monthlySales: 9200, rating: 4.5, createdAt: NOW - 259200000, mainImage: 'https://picsum.photos/seed/c4/400/500', shopName: 'Baseus Official', max_power: 65, sellingPoints: '轻薄便携，PD快充。' },

  // 蓝牙耳机 4 条
  { id: 'e1', period: TODAY, categoryId: 'cat_earbuds', channel: 'Amazon', brand: 'Apple', model: 'AirPods Pro 2', price: 1899, monthlySales: 15000, rating: 4.9, createdAt: NOW, mainImage: 'https://picsum.photos/seed/e1/400/500', shopName: 'Apple Store', battery_life: 6, bluetooth_version: '5.3', noise_cancelling: '主动降噪', water_resistance: 'IPX4', sellingPoints: '空间音频，自适应降噪。' },
  { id: 'e2', period: TODAY, categoryId: 'cat_earbuds', channel: 'Rakuten', brand: '索尼', model: 'WF-1000XM5', price: 1499, monthlySales: 6200, rating: 4.8, createdAt: NOW - 86400000, mainImage: 'https://picsum.photos/seed/e2/400/500', shopName: 'Sony Direct', battery_life: 8, bluetooth_version: '5.3', noise_cancelling: '主动降噪', water_resistance: 'IPX4', sellingPoints: '业界顶级降噪，LDAC高清。' },
  { id: 'e3', period: TODAY, categoryId: 'cat_earbuds', channel: 'Yahoo Shopping', brand: '华为', model: 'FreeBuds Pro 3', price: 899, monthlySales: 9800, rating: 4.7, createdAt: NOW - 172800000, mainImage: 'https://picsum.photos/seed/e3/400/500', shopName: 'Huawei VMall', battery_life: 7, bluetooth_version: '5.3', noise_cancelling: '主动降噪', water_resistance: 'IPX4', sellingPoints: '超感知降噪，麒麟A2芯片。' },
  { id: 'e4', period: TODAY, categoryId: 'cat_earbuds', channel: 'Amazon', brand: '小米', model: 'Buds 4 Pro', price: 699, monthlySales: 11000, rating: 4.6, createdAt: NOW - 259200000, mainImage: 'https://picsum.photos/seed/e4/400/500', shopName: 'Xiaomi Global', battery_life: 9, bluetooth_version: '5.3', noise_cancelling: '主动降噪', water_resistance: 'IPX4', sellingPoints: '48dB降噪，高性价比。' },

  // 智能手表 4 条
  { id: 's1', period: TODAY, categoryId: 'cat_smartwatch', channel: 'Amazon', brand: 'Apple', model: 'Watch Ultra 2', price: 6499, monthlySales: 4200, rating: 4.9, createdAt: NOW, mainImage: 'https://picsum.photos/seed/s1/400/500', shopName: 'Apple Store', screen_size: 1.92, battery_days: 2, water_resistance: '100m', sellingPoints: '钛金属表壳，双频GPS，潜水级。' },
  { id: 's2', period: TODAY, categoryId: 'cat_smartwatch', channel: 'Rakuten', brand: '华为', model: 'Watch GT 4', price: 1488, monthlySales: 8500, rating: 4.8, createdAt: NOW - 86400000, mainImage: 'https://picsum.photos/seed/s2/400/500', shopName: 'Huawei VMall', screen_size: 1.43, battery_days: 14, water_resistance: '50m', sellingPoints: '超长续航，健康管理全面。' },
  { id: 's3', period: TODAY, categoryId: 'cat_smartwatch', channel: 'Yahoo Shopping', brand: '小米', model: 'Watch S3', price: 999, monthlySales: 12000, rating: 4.6, createdAt: NOW - 172800000, mainImage: 'https://picsum.photos/seed/s3/400/500', shopName: 'Xiaomi Global', screen_size: 1.43, battery_days: 15, water_resistance: '50m', sellingPoints: '澎湃OS，百变表圈。' },
  { id: 's4', period: TODAY, categoryId: 'cat_smartwatch', channel: 'Amazon', brand: 'OPPO', model: 'Watch 4 Pro', price: 2299, monthlySales: 3600, rating: 4.7, createdAt: NOW - 259200000, mainImage: 'https://picsum.photos/seed/s4/400/500', shopName: 'OPPO Store', screen_size: 1.91, battery_days: 5, water_resistance: '50m', sellingPoints: '骁龙W5，eSIM独立通话。' },

  // 笔记本电脑 4 条
  { id: 'l1', period: TODAY, categoryId: 'cat_laptop', channel: 'Amazon', brand: 'Apple', model: 'MacBook Pro 14 M3 Pro', price: 14999, monthlySales: 2800, rating: 4.9, createdAt: NOW, mainImage: 'https://picsum.photos/seed/l1/400/500', shopName: 'Apple Store', cpu_model: 'M3 Pro', ram_gb: 18, storage_gb: 512, screen_size: 14.2, weight_kg: 1.55, sellingPoints: '专业创作，ProMotion屏幕。' },
  { id: 'l2', period: TODAY, categoryId: 'cat_laptop', channel: 'Rakuten', brand: '联想', model: 'ThinkPad X1 Carbon', price: 9999, monthlySales: 4500, rating: 4.7, createdAt: NOW - 86400000, mainImage: 'https://picsum.photos/seed/l2/400/500', shopName: 'Lenovo Direct', cpu_model: 'i7-1365U', ram_gb: 16, storage_gb: 512, screen_size: 14, weight_kg: 1.12, sellingPoints: '商务标杆，军工级耐用。' },
  { id: 'l3', period: TODAY, categoryId: 'cat_laptop', channel: 'Yahoo Shopping', brand: '华为', model: 'MateBook X Pro', price: 8999, monthlySales: 6200, rating: 4.8, createdAt: NOW - 172800000, mainImage: 'https://picsum.photos/seed/l3/400/500', shopName: 'Huawei VMall', cpu_model: 'i7-1360P', ram_gb: 16, storage_gb: 512, screen_size: 14.2, weight_kg: 1.26, sellingPoints: '3.1K触控屏，超级终端。' },
  { id: 'l4', period: TODAY, categoryId: 'cat_laptop', channel: 'Amazon', brand: '小米', model: 'RedmiBook Pro 15', price: 4999, monthlySales: 9500, rating: 4.5, createdAt: NOW - 259200000, mainImage: 'https://picsum.photos/seed/l4/400/500', shopName: 'Xiaomi Global', cpu_model: 'i5-13500H', ram_gb: 16, storage_gb: 512, screen_size: 15.6, weight_kg: 1.78, sellingPoints: '3.2K高刷屏，高性价比。' },

  // 智能手机 5 条
  { id: 'p1', period: TODAY, categoryId: 'cat_phone', channel: 'Amazon', brand: 'Apple', model: 'iPhone 15 Pro Max', price: 9999, monthlySales: 22000, rating: 4.9, createdAt: NOW, mainImage: 'https://picsum.photos/seed/p1/400/500', shopName: 'Apple Store', screen_size: 6.7, ram_gb: 8, storage_gb: 256, battery_mah: 4422, network_5g: '支持', sellingPoints: 'A17 Pro，钛金属，动作按钮。' },
  { id: 'p2', period: TODAY, categoryId: 'cat_phone', channel: 'Rakuten', brand: '华为', model: 'Mate 60 Pro+', price: 8999, monthlySales: 18000, rating: 4.8, createdAt: NOW - 86400000, mainImage: 'https://picsum.photos/seed/p2/400/500', shopName: 'Huawei VMall', screen_size: 6.82, ram_gb: 12, storage_gb: 512, battery_mah: 5000, network_5g: '支持', sellingPoints: '麒麟9000s，卫星通信，鸿蒙4。' },
  { id: 'p3', period: TODAY, categoryId: 'cat_phone', channel: 'Yahoo Shopping', brand: '小米', model: '14 Ultra', price: 5999, monthlySales: 12000, rating: 4.7, createdAt: NOW - 172800000, mainImage: 'https://picsum.photos/seed/p3/400/500', shopName: 'Xiaomi Global', screen_size: 6.73, ram_gb: 16, storage_gb: 512, battery_mah: 5000, network_5g: '支持', sellingPoints: '徕卡Summilux，可变光圈。' },
  { id: 'p4', period: TODAY, categoryId: 'cat_phone', channel: 'Amazon', brand: 'OPPO', model: 'Find X7 Ultra', price: 5999, monthlySales: 8500, rating: 4.8, createdAt: NOW - 259200000, mainImage: 'https://picsum.photos/seed/p4/400/500', shopName: 'OPPO Store', screen_size: 6.82, ram_gb: 16, storage_gb: 512, battery_mah: 5000, network_5g: '支持', sellingPoints: '双潜望长焦，哈苏影像。' },
  { id: 'p5', period: TODAY, categoryId: 'cat_phone', channel: 'Rakuten', brand: 'vivo', model: 'X100 Pro', price: 4999, monthlySales: 14000, rating: 4.7, createdAt: NOW - 345600000, mainImage: 'https://picsum.photos/seed/p5/400/500', shopName: 'vivo Direct', screen_size: 6.78, ram_gb: 16, storage_gb: 512, battery_mah: 5400, network_5g: '支持', sellingPoints: '天玑9300，蔡司APO长焦。' },
];

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'cat_powerbank', name: '充电宝', fields: POWERBANK_FIELDS },
  { id: 'cat_charger', name: '充电器/适配器', fields: CHARGER_FIELDS },
  { id: 'cat_earbuds', name: '蓝牙耳机', fields: EARBUDS_FIELDS },
  { id: 'cat_smartwatch', name: '智能手表', fields: SMARTWATCH_FIELDS },
  { id: 'cat_laptop', name: '笔记本电脑', fields: LAPTOP_FIELDS },
  { id: 'cat_phone', name: '智能手机', fields: PHONE_FIELDS },
];
