
import { ProductField, FieldType, Category, ProductData, Language } from './types';

export const APP_NAME = "Smart Hub";
export const STORAGE_KEY = "smart_hub_v6_production";
export const DEPLOY_NODE = "PROD-CLOUD-LIVE-01";

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    dashboard: "Dashboard",
    inventory: "Inventory",
    settings: "Field Architect",
    users: "Team Security",
    logout: "Log Out",
    profile_settings: "Profile Protocol",
    authenticated_entity: "Authenticated Entity",
    identifier: "Identifier",
    login_email: "Email",
    login_password: "Password",
    forgot_password: "Forgot password?",
    forgot_password_hint: "Enter your login email to receive a reset link",
    reset_email_sent: "Reset link sent. Check your email.",
    send_reset_link: "Send Reset Link",
    auth_reset_user_not_found: "User with this email not found",
    auth_reset_rate_limit: "Please wait 60 seconds before requesting again",
    auth_reset_invalid_email: "Invalid email format",
    auth_reset_failed: "Request failed, please try again",
    security_key: "Security Key",
    connection_established: "Establish Connection",
    status_ready: "SKUs Active",
    last_saved: "Last Node Sync",
    all: "Global All",
    no_data: "No Protocol Found",
    count: "Count",
    category: "Category",
    channel: "Channel",
    brand: "Brand",
    model: "Model/SKU",
    new_entry: "New Entry",
    paste_import: "Paste to Import",
    paste_import_hint: "Paste detail page content or GPT extraction result; parse to fill the form in one step.",
    paste_placeholder: "Paste product detail text here...",
    parse_and_fill: "Parse & Fill Form",
    parse_loading: "Parsing...",
    parse_error: "Parse failed. Check text format or try again.",
    fetch_and_parse: "Fetch Page & Parse",
    fetch_and_parse_hint: "Paste a detail page URL; we fetch the page and parse it into the form.",
    paste_in_form_hint: "After selecting category, paste link or text here; AI fills only the fields defined for this category (set in Field Architect).",
    expand_more_hint: "If the page has \"Load more\" or dynamic content, expand it in the browser and copy the full text, or paste the link to GPT to fetch full content, then paste here.",
    fetch_loading: "Fetching page...",
    fetch_error: "Failed to fetch page.",
    add_info: "Save Protocol",
    cancel: "Cancel",
    edit: "Modify Node",
    delete: "Purge",
    report_pdf: "Export Analysis",
    reset: "Reset Matrix",
    close: "Terminate Session",
    ai_insights: "AI Market Intelligence",
    generate_insight: "Generate Strategy Report",
    analyzing: "AI Analyzing Global Data...",
    search_placeholder: "Search SKU, Brand, Keywords...",
    ai_analysis_btn: "AI Deep Analysis",
    market_share: "Market Share",
    provision_access: "Provision Member",
    edit_user: "Edit Access Policy",
    clearance: "Clearance Level",
    execute_provision: "Execute Provision",
    save_changes: "Commit Changes",
    delete_confirm: "Permanently purge this record from cloud?",
    price_index: "Price Index",
    monthly_movement: "Monthly Velocity",
    options_config: "Options (Comma Separated)",
    field_name: "Node Identifier",
    field_type: "Data Modality",
    add_node: "Append Node",
    save_node: "Save Node",
    market_intel: "Market Intelligence",
    benchmarking_protocol: "Advanced Functional Benchmarking Protocol",
    global_channels: "Global Channels",
    all_brands: "All Brands",
    ai_tactical_analysis: "AI Tactical Analysis",
    market_penetration: "Market Penetration",
    segment_coverage: "Full segment view",
    price_competitiveness: "Price Position",
    segment_volume: "Segment Volume",
    rating: "Rating",
    price: "Price",
    sales: "Sales",
    volume: "Volume",
    units: "Units",
    leaderboard: "Market Leaderboard",
    ranking_velocity: "Ranking by Unit Velocity",
    sort_by_sales: "Sales",
    sort_by_price: "Price",
    sort_by_rating: "Rating",
    others: "Others",
    rating_distribution: "Rating Distribution",
    products_by_rating: "Products by rating range",
    skus_tracked: "SKUs TRACKED",
    market_value: "Market Value",
    velocity: "Velocity",
    expand_waterfall: "EXPAND MARKET WATERFALL",
    ai_lock_hint: "Select Category & Channel for precision AI analysis",
    ai_ready: "AI Node Active: Ready for Analysis",
    full_node_data: "Full Node Intelligence Data",
    visit_link: "Open Source Link",
    price_vs_sales: "Price vs Sales Volume Matrix",
    price_sales_matrix: "Price vs Sales Volume Matrix",
    units_current_view: "Units in current view",
    ai_generated_via: "Generated via Gemini",
    product_sell_points: "Product Selling Points",
    customer_voice_analysis: "Customer Voice Analysis",
    critical_pain_point: "Critical Customer Pain Point",
    market_opportunity_analysis: "Market Opportunity Analysis",
    category_share: "Brand Market Share",
    vs_global_avg: "VS SEGMENT AVG",
    select_architecture: "Select Data Architecture",
    node_definition_mode: "Node Definition Mode",
    syncing: "Syncing",
    cloud_active: "Cloud Active",
    view_detail: "View Details",
    product_item: "this product",
    select_category: "Select Product Category",
    select_category_hint: "Select category for new product",
    fields_count: "fields",
    cancel_select: "Cancel",
    core_info: "Core Info",
    core_info_hint: "Brand, model, channel, shop, price, etc.",
    brand_placeholder: "Enter brand",
    model_placeholder: "Enter model",
    select_channel: "Select channel",
    shop_name: "Shop Name",
    shop_name_placeholder: "Enter shop name",
    price_label: "Price (¥)",
    actual_price: "Actual Price / After Coupon",
    monthly_sales: "Monthly Sales",
    units_per_month: "units/mo",
    rating_label: "Rating (0-5)",
    link_url: "Product Link",
    main_image: "Main Image",
    main_image_placeholder: "Upload main image",
    main_image_url: "Main Image URL",
    category_params: "Category Params",
    category_params_hint: "Auto-updates with backend",
    basic_product_info: "Basic Product Information",
    category_name: "Category",
    created_at: "Created",
    updated_at: "Updated",
    not_set: "Not Set",
    unknown: "Unknown",
    set: "Set",
    product_detail_title: "Product Detail",
    visit_source_link: "Visit Link",
    ai_analyzing: "AI Analyzing...",
    ai_deep_analysis: "AI Deep Analysis",
    ai_competitor_strategy: "AI Competitor Strategy",
    edit_product_info: "Edit Product",
    modify: "Modify",
    delete_confirm_product: "Delete «{name}»? This cannot be undone.",
    brand_required: "Brand required",
    model_required: "Model required",
    channel_required: "Channel required",
    save_failed: "Save failed, check data format",
    pagination_show: "Show {start}-{end} of {total}",
    per_page: "per page",
    no_data_caption: "No data",
    sell_points: "Selling Points (comma separated)",
    pros: "Pros",
    cons: "Cons",
    pain_point: "Pain Point",
    insight_summary: "Market Insight",
    unknown_brand: "Unknown Brand",
    unknown_channel: "Unknown Channel",
    login_id: "Login ID",
    unnamed_product: "Unnamed Product",
    protocol_access: "Autonomous Protocol Access",
    validating_token: "Validating Token...",
    login_failed: "Login sequence failed: Identity or Key mismatch",
    login_profile_not_found: "User profile not found. Run: node scripts/ensure-default-auth.js",
    invalid_supabase_key: "Supabase API key invalid or not set. Check SUPABASE_URL and SUPABASE_ANON_KEY in Vercel (or .env locally).",
    connection_failed: "Connection failed",
    auth_timeout: "Connection timed out. Check network or Supabase status (status.supabase.com).",
    cloud_sync_active: "Cloud Sync Active: Supabase Cloud Infrastructure",
    design_by: "Design by",
    footer_attribution: "Designed by ALEX © 2026",
    reset_cache_confirm: "System data reset. Local cache will be cleared, cloud data remains. Proceed?",
    hard_reset_cache: "Hard Reset Cache",
    email_placeholder: "user@company.com",
    users_subtitle: "Team Security Configuration",
    new_clearance: "New Clearance",
    add_member_subtitle: "Add new member",
    username_placeholder: "Username or email",
    password_placeholder: "Password",
    password_placeholder_optional: "Password (leave blank to keep)",
    username_exists: "Username or email already exists",
    edit_member_subtitle: "Edit member info",
    entity_identifier: "Entity Identifier",
    security: "Security",
    protocol: "Protocol",
    role_viewer: "Viewer",
    role_editor: "Editor",
    role_admin: "Admin",
    diagnostic_title: "System Protocol Diagnostic",
    resync_node: "Re-sync Node",
    acknowledge: "Acknowledge",
    auth_expired: "Session expired, please log in again",
    create_user_failed: "Create user failed",
    sync_failed: "Sync failed",
    system_architect: "System Architect",
    data_analyst: "Data Analyst",
    main_image_paste_hint: "Paste image URL (right-click product image on e-commerce page, copy image address, then Ctrl+V)",
    or_upload_local: "Or click to upload local image",
    upload_to_cloud: "Save to Cloud",
    upload_failed: "Upload failed",
    image_uploading: "Uploading...",
    upload_cancelled: "Upload cancelled",
    save_with_link_hint: "You can save now with the current image link, or cancel upload.",
    ai_response_empty: "AI response is empty",
    ai_analysis_interrupted: "Analysis interrupted",
    ai_competitor_blocked: "AI competitor analysis blocked, please retry later",
    premium_pos: "Premium Pos",
    budget_pos: "Budget Pos",
    ready: "Ready",
    done: "Done",
    core_sell_points: "Core Selling Points",
    review_compare: "Review Compare",
    pros_wordcloud: "Pros Word Cloud",
    cons_wordcloud: "Cons Word Cloud",
    key_pain_point: "Key Pain Point",
    jarvis_insight: "Jarvis Insight",
    ai_node_blocked: "AI analysis blocked",
    core_fields: "Core Fields",
    core_fields_hint: "Shared by all categories, not editable",
    fixed: "Fixed",
    category_params_label: "Category Params",
    category_specific_hint: "{name} specific attributes",
    add_product_failed: "Add product failed",
    save_timeout: "Request timed out. Check network or try again.",
    save_aborted: "Request was cancelled or interrupted. Please try again.",
    update_product_failed: "Update product failed",
    update_category_failed: "Update category failed",
    field_types: {
      text: "Text Input",
      number: "Numeric Value",
      url: "Web URL",
      image: "Visual Data",
      textarea: "Rich Text",
      rating: "Star Rating",
      select: "Single Selection",
      date: "System Date",
      multi_select_quantity: "Multi-Quantity"
    }
  },
  zh: {
    dashboard: "数据概览",
    inventory: "产品管理",
    settings: "调研架构",
    users: "团队安全",
    logout: "安全退出",
    profile_settings: "个人资料",
    authenticated_entity: "已验证实体",
    identifier: "登录账户",
    login_email: "邮箱",
    login_password: "密码",
    forgot_password: "找回密码",
    forgot_password_hint: "输入登录邮箱以接收重置链接",
    reset_email_sent: "重置链接已发送，请查收邮件",
    send_reset_link: "发送重置链接",
    auth_reset_user_not_found: "该邮箱未注册",
    auth_reset_rate_limit: "请等待 60 秒后再试",
    auth_reset_invalid_email: "邮箱格式无效",
    auth_reset_failed: "请求失败，请稍后重试",
    security_key: "安全密码",
    connection_established: "建立系统连接",
    status_ready: "条目已就绪",
    last_saved: "同步时间",
    all: "全部显示",
    no_data: "暂无数据条目",
    count: "数量",
    category: "品类架构",
    channel: "渠道/平台",
    brand: "品牌",
    model: "产品名/型号",
    new_entry: "录入条目",
    paste_import: "从文本录入",
    paste_import_hint: "粘贴详情页内容或 GPT 抓取结果，解析后自动填入表单，无需再复制到表格。",
    paste_placeholder: "在此粘贴产品详情内容或 GPT 输出的文本...",
    parse_and_fill: "解析并填入表单",
    parse_loading: "解析中...",
    parse_error: "解析失败，请检查文本格式或重试。",
    fetch_and_parse: "拉取页面并解析",
    fetch_and_parse_hint: "粘贴详情页链接，由系统拉取页面内容并解析为表单。",
    paste_in_form_hint: "选品类后在此粘贴链接或文本，AI 仅按当前品类已建字段填入。品类字段需在「调研架构」中先建好。",
    expand_more_hint: "若页面有「展开更多」等动态内容，请先在浏览器中展开后复制全文，或将链接发给 GPT 抓取完整内容后粘贴此处。",
    fetch_loading: "正在拉取页面...",
    fetch_error: "拉取页面失败。",
    add_info: "保存配置",
    cancel: "取消操作",
    edit: "修改节点",
    delete: "永久删除",
    report_pdf: "导出调研报表",
    reset: "重置筛选",
    close: "关闭窗口",
    ai_insights: "AI 市场洞察",
    generate_insight: "生成市场分析策略",
    analyzing: "AI 正在分析全域数据...",
    search_placeholder: "搜索品牌、型号、卖点或差评关键词...",
    ai_analysis_btn: "AI 单品深度分析",
    market_share: "市场份额",
    provision_access: "授权新成员",
    edit_user: "修改成员权限",
    clearance: "权限层级",
    execute_provision: "执行授权",
    save_changes: "保存更改",
    delete_confirm: "确认从云端永久删除此条目？",
    price_index: "价格对标指数",
    monthly_movement: "月度动向",
    options_config: "选项配置 (以逗号分隔)",
    field_name: "字段名称",
    field_type: "数据类型",
    add_node: "添加字段节点",
    save_node: "保存字段",
    market_intel: "市场情报中心",
    benchmarking_protocol: "高级功能基准分析协议",
    global_channels: "全球渠道总览",
    all_brands: "全品牌列表",
    ai_tactical_analysis: "AI 战术分析报告",
    market_penetration: "市场渗透率",
    segment_coverage: "当前细分全量",
    price_competitiveness: "价格定位指数",
    segment_volume: "细分市场销量",
    rating: "评分",
    price: "价格",
    sales: "销量",
    volume: "销量",
    units: "件",
    leaderboard: "单品销量排行榜",
    ranking_velocity: "基于月度销量的实时排名",
    sort_by_sales: "销量",
    sort_by_price: "价格",
    sort_by_rating: "评分",
    others: "其他",
    rating_distribution: "评分分布",
    products_by_rating: "按评分区间统计",
    skus_tracked: "个活跃单品被追踪",
    market_value: "市场价格",
    velocity: "销售动向",
    expand_waterfall: "展开更多市场数据",
    ai_lock_hint: "请先选择具体品类和平台以开启 AI 精准分析",
    ai_ready: "AI 节点就绪：可进行市场深度分析",
    full_node_data: "全量情报节点数据",
    visit_link: "访问原始链接",
    price_vs_sales: "价格与销量关系矩阵",
    price_sales_matrix: "价格 vs 销量矩阵",
    units_current_view: "当前视图销量",
    ai_generated_via: "由 Gemini 生成",
    product_sell_points: "产品卖点",
    customer_voice_analysis: "口碑分析",
    critical_pain_point: "关键用户痛点",
    market_opportunity_analysis: "市场机会分析",
    category_share: "品牌销量占比分布",
    vs_global_avg: "对比市场细分均价",
    select_architecture: "选择录入的数据架构",
    node_definition_mode: "节点定义编辑模式",
    syncing: "同步中",
    cloud_active: "云端在线",
    view_detail: "查看详情",
    product_item: "该产品",
    select_category: "选择产品品类",
    select_category_hint: "请选择要添加的产品品类架构",
    fields_count: "个字段",
    cancel_select: "取消选择",
    core_info: "核心信息",
    core_info_hint: "品牌、型号、渠道、店铺名、价格等",
    brand_placeholder: "输入品牌名称",
    model_placeholder: "输入产品型号",
    select_channel: "选择渠道",
    shop_name: "店铺名",
    shop_name_placeholder: "输入店铺名称",
    price_label: "价格 (¥)",
    actual_price: "到手价/券后",
    monthly_sales: "月销量",
    units_per_month: "件/月",
    rating_label: "评分 (0-5)",
    link_url: "产品链接",
    main_image: "主图",
    main_image_placeholder: "上传产品主图",
    main_image_url: "主图链接",
    category_params: "品类参数",
    category_params_hint: "随后台字段自动更新",
    basic_product_info: "产品基础信息",
    category_name: "品类",
    created_at: "创建时间",
    updated_at: "更新时间",
    not_set: "未设置",
    unknown: "未知",
    set: "已设置",
    product_detail_title: "竞品情报详情",
    visit_source_link: "前往源链接",
    ai_analyzing: "AI 分析中...",
    ai_deep_analysis: "AI 单品深度分析",
    ai_competitor_strategy: "AI 竞品对策",
    edit_product_info: "编辑产品信息",
    modify: "修改",
    delete_confirm_product: "确定要删除「{name}」吗？此操作不可撤销。",
    brand_required: "请填写品牌名称",
    model_required: "请填写产品型号",
    channel_required: "请填写销售渠道",
    save_failed: "保存失败，请检查数据格式",
    pagination_show: "显示 {start}-{end} / {total} 条",
    per_page: "条/页",
    no_data_caption: "暂无数据",
    sell_points: "卖点（用逗号分隔）",
    pros: "好评",
    cons: "差评",
    pain_point: "关键痛点",
    insight_summary: "市场洞察",
    unknown_brand: "未知品牌",
    unknown_channel: "未知渠道",
    login_id: "登录ID",
    unnamed_product: "未命名产品",
    protocol_access: "自主协议访问",
    validating_token: "正在验证凭证...",
    login_failed: "登录失败：身份或密钥不匹配",
    login_profile_not_found: "未找到用户档案，请运行：node scripts/ensure-default-auth.js",
    invalid_supabase_key: "Supabase API 密钥无效或未配置。请在 Vercel 环境变量（或本地 .env）中检查 SUPABASE_URL 和 SUPABASE_ANON_KEY。",
    connection_failed: "连接失败",
    auth_timeout: "连接超时，请检查网络或 Supabase 服务状态（status.supabase.com）。",
    cloud_sync_active: "云端同步已启用：Supabase 云基础设施",
    design_by: "设计",
    footer_attribution: "Designed by ALEX © 2026",
    reset_cache_confirm: "系统数据重置。将清除本地缓存，云端数据保留。是否继续？",
    hard_reset_cache: "强制重置缓存",
    email_placeholder: "user@company.com",
    users_subtitle: "团队安全配置",
    new_clearance: "新建授权",
    add_member_subtitle: "添加新成员",
    username_placeholder: "用户名或邮箱",
    password_placeholder: "密码",
    password_placeholder_optional: "密码（留空不修改）",
    username_exists: "用户名或邮箱已存在",
    edit_member_subtitle: "修改成员信息",
    entity_identifier: "实体标识",
    security: "安全",
    protocol: "协议",
    role_viewer: "查看者",
    role_editor: "编辑者",
    role_admin: "管理员",
    diagnostic_title: "系统协议诊断",
    resync_node: "重新同步",
    acknowledge: "确认",
    auth_expired: "登录已过期，请重新登录",
    create_user_failed: "创建用户失败",
    sync_failed: "同步失败",
    system_architect: "系统架构师",
    data_analyst: "数据分析师",
    main_image_paste_hint: "粘贴图片链接（从电商页右键主图「复制图片地址」后 Ctrl+V）",
    or_upload_local: "或点击上传本地图片",
    upload_to_cloud: "保存到云端",
    upload_failed: "上传失败",
    image_uploading: "上传中...",
    upload_cancelled: "已取消上传",
    save_with_link_hint: "可直接点「保存」使用当前图片链接，或取消上传",
    ai_response_empty: "AI 响应内容为空",
    ai_analysis_interrupted: "分析中断",
    ai_competitor_blocked: "AI 竞品分析受阻，请稍后重试",
    premium_pos: "高端定位",
    budget_pos: "性价比定位",
    ready: "就绪",
    done: "完成",
    core_sell_points: "核心卖点",
    review_compare: "口碑对比",
    pros_wordcloud: "好评词云",
    cons_wordcloud: "差评词云",
    key_pain_point: "关键痛点",
    jarvis_insight: "贾维斯洞察",
    ai_node_blocked: "AI 分析节点受阻",
    core_fields: "核心字段",
    core_fields_hint: "所有品类共有，不可编辑",
    fixed: "固定",
    category_params_label: "品类参数",
    category_specific_hint: "{name} 特有属性",
    add_product_failed: "添加产品失败",
    save_timeout: "请求超时，请检查网络或稍后重试。",
    save_aborted: "请求被取消或中断，请重试。",
    update_product_failed: "更新产品失败",
    update_category_failed: "更新品类失败",
    field_types: {
      text: "短文本录入",
      number: "数值/金额",
      url: "网页链接",
      image: "调研主图",
      textarea: "长文本/多行",
      rating: "星级评分",
      select: "单选下拉框",
      date: "系统日期选择",
      multi_select_quantity: "多选带数量"
    }
  },
  ja: {
    dashboard: "ダッシュボード",
    inventory: "製品管理",
    settings: "調査構成",
    users: "チーム管理",
    logout: "ログアウト",
    profile_settings: "プロファイル設定",
    authenticated_entity: "認証済み",
    identifier: "アカウント",
    login_email: "メール",
    login_password: "パスワード",
    forgot_password: "パスワードを忘れた",
    forgot_password_hint: "ログイン用メールアドレスを入力してリセットリンクを受け取る",
    reset_email_sent: "リセットリンクを送信しました。メールをご確認ください。",
    send_reset_link: "リセットリンクを送信",
    auth_reset_user_not_found: "このメールアドレスは登録されていません",
    auth_reset_rate_limit: "60秒後に再度お試しください",
    auth_reset_invalid_email: "メール形式が無効です",
    auth_reset_failed: "リクエストに失敗しました。しばらくしてからお試しください",
    security_key: "パスワード",
    connection_established: "接続開始",
    status_ready: "有効データ",
    last_saved: "最終同期",
    all: "すべて表示",
    no_data: "データが見つかりません",
    count: "件数",
    category: "カテゴリ構成",
    channel: "チャネル/プラットフォーム",
    brand: "ブランド",
    model: "モデル/型番",
    new_entry: "新規登録",
    paste_import: "テキストから登録",
    paste_import_hint: "詳細ページの内容またはGPT抽出結果を貼り付け、解析してフォームに反映。",
    paste_placeholder: "ここに商品詳細テキストを貼り付け...",
    parse_and_fill: "解析してフォームに反映",
    parse_loading: "解析中...",
    parse_error: "解析に失敗しました。テキスト形式を確認するか、再試行してください。",
    fetch_and_parse: "ページ取得して解析",
    fetch_and_parse_hint: "詳細ページURLを貼り付け、システムが取得・解析します。",
    paste_in_form_hint: "カテゴリ選択後、ここにリンクまたはテキストを貼り付け。AIはこのカテゴリの既存フィールドのみ入力（フィールドは「ノード定義」で事前に作成）。",
    expand_more_hint: "ページに「もっと見る」等の動的コンテンツがある場合は、ブラウザで展開して全文をコピーするか、GPTにリンクを渡して取得した内容を貼り付けてください。",
    fetch_loading: "ページ取得中...",
    fetch_error: "ページ取得に失敗しました。",
    add_info: "プロトコル保存",
    cancel: "キャンセル",
    edit: "ノード編集",
    delete: "削除",
    report_pdf: "レポート出力",
    reset: "フィルターリセット",
    close: "閉じる",
    ai_insights: "AI戦略インサイト",
    generate_insight: "戦略レポート作成",
    analyzing: "AIがデータを分析中...",
    search_placeholder: "ブランド、型番、キーワードを検索...",
    ai_analysis_btn: "AI詳細分析",
    market_share: "市場シェア",
    provision_access: "メンバー招待",
    edit_user: "権限ポリシー編集",
    clearance: "権限レベル",
    execute_provision: "招待を実行",
    save_changes: "変更を保存",
    delete_confirm: "このデータを完全に削除しますか？",
    price_index: "価格指数",
    monthly_movement: "月間動向",
    options_config: "オプション (カンマ区切り)",
    field_name: "ノード名",
    field_type: "データ形式",
    add_node: "ノード追加",
    save_node: "ノード保存",
    market_intel: "市場インテリジェンス",
    benchmarking_protocol: "高度な機能ベンチマーク",
    global_channels: "グローバルチャネル",
    all_brands: "すべてのブランド",
    ai_tactical_analysis: "AI戦術分析レポート",
    market_penetration: "市場シェア率",
    segment_coverage: "セグメント全量表示",
    price_competitiveness: "価格ポジション",
    segment_volume: "セグメント販売数",
    rating: "評価",
    price: "価格",
    sales: "販売数",
    volume: "販売数",
    units: "個",
    leaderboard: "マーケットリーダーボード",
    ranking_velocity: "販売速度によるランキング",
    sort_by_sales: "販売数",
    sort_by_price: "価格",
    sort_by_rating: "評価",
    others: "その他",
    rating_distribution: "評価分布",
    products_by_rating: "評価帯別製品数",
    skus_tracked: "個のSKUを追跡中",
    market_value: "市場価格",
    velocity: "販売動向",
    expand_waterfall: "さらに表示",
    ai_lock_hint: "精密分析のためにカテゴリとチャネルを選択してください",
    ai_ready: "AIノード有効：分析準備完了",
    full_node_data: "フルインテリジェンスデータ",
    visit_link: "リンクを開く",
    price_vs_sales: "価格と販売数のマトリックス",
    price_sales_matrix: "価格 vs 販売量マトリクス",
    units_current_view: "現在表示中の販売数",
    ai_generated_via: "Gemini により生成",
    product_sell_points: "製品の売りポイント",
    customer_voice_analysis: "顧客の声分析",
    critical_pain_point: "重要な顧客課題",
    market_opportunity_analysis: "市場機会分析",
    category_share: "ブランド別シェア分布",
    vs_global_avg: "セグメント平均との比較",
    select_architecture: "データアーキテクチャの選択",
    node_definition_mode: "ノード定義モード",
    syncing: "同期中",
    cloud_active: "クラウド接続",
    view_detail: "詳細を表示",
    product_item: "この製品",
    select_category: "製品カテゴリを選択",
    select_category_hint: "追加する製品のカテゴリを選択",
    fields_count: "個のフィールド",
    cancel_select: "キャンセル",
    core_info: "基本情報",
    core_info_hint: "ブランド、型番、チャネル、店舗名、価格など",
    brand_placeholder: "ブランド名を入力",
    model_placeholder: "型番を入力",
    select_channel: "チャネルを選択",
    shop_name: "店舗名",
    shop_name_placeholder: "店舗名を入力",
    price_label: "価格 (¥)",
    actual_price: "実質価格/クーポン後",
    monthly_sales: "月間販売数",
    units_per_month: "件/月",
    rating_label: "評価 (0-5)",
    link_url: "製品リンク",
    main_image: "メイン画像",
    main_image_placeholder: "メイン画像をアップロード",
    main_image_url: "メイン画像URL",
    category_params: "カテゴリパラメータ",
    category_params_hint: "バックエンドに自動更新",
    basic_product_info: "製品基本情報",
    category_name: "カテゴリ",
    created_at: "作成日時",
    updated_at: "更新日時",
    not_set: "未設定",
    unknown: "不明",
    set: "設定済み",
    product_detail_title: "製品詳細",
    visit_source_link: "リンクを開く",
    ai_analyzing: "AI 分析中...",
    ai_deep_analysis: "AI 詳細分析",
    ai_competitor_strategy: "AI 競合対策",
    edit_product_info: "製品情報を編集",
    modify: "編集",
    delete_confirm_product: "「{name}」を削除しますか？元に戻せません。",
    brand_required: "ブランド名を入力してください",
    model_required: "型番を入力してください",
    channel_required: "チャネルを選択してください",
    save_failed: "保存に失敗しました。データ形式を確認してください",
    pagination_show: "{start}-{end} / {total} 件を表示",
    per_page: "件/ページ",
    no_data_caption: "データなし",
    sell_points: "売りポイント（カンマ区切り）",
    pros: "高評価",
    cons: "低評価",
    pain_point: "重要な課題",
    insight_summary: "市場インサイト",
    unknown_brand: "不明なブランド",
    unknown_channel: "不明なチャネル",
    login_id: "ログインID",
    unnamed_product: "未命名製品",
    protocol_access: "自律プロトコルアクセス",
    validating_token: "トークン検証中...",
    login_failed: "ログイン失敗：IDまたはキーが一致しません",
    login_profile_not_found: "ユーザープロファイルが見つかりません。node scripts/ensure-default-auth.js を実行してください",
    invalid_supabase_key: "Supabase API キーが無効または未設定です。Vercel の環境変数（またはローカル .env）で SUPABASE_URL と SUPABASE_ANON_KEY を確認してください。",
    connection_failed: "接続に失敗しました",
    auth_timeout: "接続がタイムアウトしました。ネットワークまたは Supabase の状態（status.supabase.com）を確認してください。",
    cloud_sync_active: "クラウド同期有効：Supabase インフラ",
    design_by: "デザイン",
    footer_attribution: "Designed by ALEX © 2026",
    reset_cache_confirm: "システムデータリセット。ローカルキャッシュをクリアします。続行しますか？",
    hard_reset_cache: "キャッシュ強制リセット",
    email_placeholder: "user@company.com",
    users_subtitle: "チームセキュリティ設定",
    new_clearance: "新規権限付与",
    add_member_subtitle: "新規メンバーを追加",
    username_placeholder: "ユーザー名またはメール",
    password_placeholder: "パスワード",
    password_placeholder_optional: "パスワード（空欄で変更なし）",
    username_exists: "ユーザー名またはメールが既に存在します",
    edit_member_subtitle: "メンバー情報を編集",
    entity_identifier: "エンティティID",
    security: "セキュリティ",
    protocol: "プロトコル",
    role_viewer: "閲覧者",
    role_editor: "編集者",
    role_admin: "管理者",
    diagnostic_title: "システムプロトコル診断",
    resync_node: "再同期",
    acknowledge: "確認",
    auth_expired: "セッション期限切れ。再ログインしてください",
    create_user_failed: "ユーザー作成に失敗しました",
    sync_failed: "同期に失敗しました",
    system_architect: "システムアーキテクト",
    data_analyst: "データアナリスト",
    main_image_paste_hint: "画像URLを貼り付け（ECサイトで画像を右クリック→画像アドレスをコピー→Ctrl+V）",
    or_upload_local: "またはクリックしてローカル画像をアップロード",
    upload_to_cloud: "クラウドに保存",
    upload_failed: "アップロード失敗",
    image_uploading: "アップロード中...",
    upload_cancelled: "アップロードをキャンセル",
    save_with_link_hint: "「保存」で現在の画像リンクを使用するか、アップロードをキャンセル",
    ai_response_empty: "AIレスポンスが空です",
    ai_analysis_interrupted: "分析中断",
    ai_competitor_blocked: "AI競合分析がブロックされました。しばらくしてから再試行してください",
    premium_pos: "プレミアム定位",
    budget_pos: "低価格定位",
    ready: "準備完了",
    done: "完了",
    core_sell_points: "コアセールスポイント",
    review_compare: "口コミ比較",
    pros_wordcloud: "高評価ワードクラウド",
    cons_wordcloud: "低評価ワードクラウド",
    key_pain_point: "重要な課題",
    jarvis_insight: "ジャービスインサイト",
    ai_node_blocked: "AI分析ノードブロック",
    core_fields: "コアフィールド",
    core_fields_hint: "全カテゴリ共通、編集不可",
    fixed: "固定",
    category_params_label: "カテゴリパラメータ",
    category_specific_hint: "{name} 固有属性",
    add_product_failed: "製品追加に失敗しました",
    save_timeout: "リクエストがタイムアウトしました。ネットワークを確認するか、しばらくして再試行してください。",
    save_aborted: "リクエストがキャンセルまたは中断されました。再試行してください。",
    update_product_failed: "製品更新に失敗しました",
    update_category_failed: "カテゴリ更新に失敗しました",
    field_types: {
      text: "テキスト入力",
      number: "数値/金額",
      url: "ウェブリンク",
      image: "画像データ",
      textarea: "長文テキスト",
      rating: "評価スコア",
      select: "単一選択",
      date: "カレンダー選択",
      multi_select_quantity: "複数選択（数量付）"
    }
  }
};

// 渠道默认选项 - 无产品数据时的兜底，实际以产品表 channel 字段为准
export const DEFAULT_CHANNEL_OPTIONS = ['Amazon', 'Rakuten', 'Yahoo Shopping'];

// 核心系统默认字段 - 固定字段，不作为动态属性
export const CORE_SYSTEM_FIELDS: ProductField[] = [
  { id: 'brand', name: '品牌', type: FieldType.TEXT, required: true },
  { id: 'model', name: '产品名/型号', type: FieldType.TEXT, required: true },
  { id: 'linkUrl', name: '产品链接', type: FieldType.URL, required: false },
  { id: 'channel', name: '渠道/平台', type: FieldType.SELECT, required: true, options: ['Amazon', 'Rakuten', 'Yahoo Shopping'] },
  { id: 'shopName', name: '店铺名', type: FieldType.TEXT, required: false },
  { id: 'price', name: '价格', type: FieldType.NUMBER, required: true },
  { id: 'actualPrice', name: '到手价/券后', type: FieldType.NUMBER, required: false },
  { id: 'monthlySales', name: '月销量', type: FieldType.NUMBER, required: false },
  { id: 'rating', name: '评分', type: FieldType.RATING, required: false },
  { id: 'mainImage', name: '主图', type: FieldType.IMAGE, required: false },
];

// 品类特定动态字段 - 新建品类默认包含（电商共性 + 调研扩展）
export const CATEGORY_SPECIFIC_FIELDS: ProductField[] = [
  { id: 'period', name: '记录日期', type: FieldType.DATE, required: true },
  { id: 'dataReliability', name: '数据可信度', type: FieldType.SELECT, required: false, options: ['高 (确凿数据)', '中 (经验估算)', '低 (仅供参考)'] },
  { id: 'placement', name: '上架位置', type: FieldType.SELECT, required: false, options: ['类目Top', '首页推荐', '搜索前列', '活动位', '其他'] },
  { id: 'search_keywords', name: '搜索关键词/入口', type: FieldType.TEXTAREA, required: false },
  { id: 'price_tier', name: '价格带', type: FieldType.SELECT, required: false, options: ['主流', '入门', '中高'] },
  { id: 'review_count', name: '评价数', type: FieldType.NUMBER, required: false },
  { id: 'selling_point_type', name: '卖点类型(主)', type: FieldType.SELECT, required: false, options: ['便携形态型', '性能效率型', '价值价格型', '生态专属型'] },
  { id: 'sellingPoints', name: '核心卖点 (USP)', type: FieldType.TEXTAREA, required: false },
  { id: 'marketDiff', name: '差异化/空白机会', type: FieldType.TEXTAREA, required: false },
  { id: 'proPoints', name: '好评高频词', type: FieldType.TEXT, required: false },
  { id: 'conPoints', name: '差评高频词', type: FieldType.TEXT, required: false },
  { id: 'targetAudience', name: '场景/人群分析', type: FieldType.TEXT, required: false },
];

// 兼容性：保持原有字段定义，但不再用于新表单
export const BASE_SYSTEM_FIELDS: ProductField[] = [
  { id: 'period', name: '记录日期', type: FieldType.DATE, required: true },
  { id: 'channel', name: '渠道/平台', type: FieldType.SELECT, required: true, options: ['Amazon', 'Rakuten', 'Yahoo Shopping'] },
  { id: 'shopName', name: '店铺名', type: FieldType.TEXT, required: false },
  { id: 'brand', name: '品牌', type: FieldType.TEXT, required: true },
  { id: 'model', name: '产品名/型号', type: FieldType.TEXT, required: true },
  { id: 'price', name: '价格(含税)', type: FieldType.NUMBER, required: true },
  { id: 'actualPrice', name: '到手价/券后', type: FieldType.NUMBER, required: false },
  { id: 'monthlySales', name: '月销量线索', type: FieldType.NUMBER, required: true },
  { id: 'rating', name: '评分', type: FieldType.RATING, required: false },
  { id: 'mainImage', name: '调研主图', type: FieldType.IMAGE, required: false },
];

export const RESEARCH_FIELDS: ProductField[] = [
  { id: 'url', name: '产品链接URL', type: FieldType.URL, required: false },
  { id: 'dataReliability', name: '数据可信度', type: FieldType.SELECT, required: false, options: ['高 (确凿数据)', '中 (经验估算)', '低 (仅供参考)'] },
  { id: 'sellingPoints', name: '核心卖点 (USP)', type: FieldType.TEXTAREA, required: false },
  { id: 'marketDiff', name: '差异化/空白机会', type: FieldType.TEXTAREA, required: false },
  { id: 'proPoints', name: '好评高频词', type: FieldType.TEXT, required: false },
  { id: 'conPoints', name: '差评高频词', type: FieldType.TEXT, required: false },
  { id: 'targetAudience', name: '场景/人群分析', type: FieldType.TEXT, required: false },
];

export const INITIAL_FIELDS: ProductField[] = [...BASE_SYSTEM_FIELDS, ...RESEARCH_FIELDS];

const TODAY = new Date().toISOString().split('T')[0];
const NOW = Date.now();

const POWERBANK_FIELDS: ProductField[] = [
  ...BASE_SYSTEM_FIELDS,
  ...RESEARCH_FIELDS,
  { id: 'capacity_mah', name: '容量 (mAh)', type: FieldType.NUMBER, required: false },
  { id: 'max_output', name: '最大输出 (W)', type: FieldType.NUMBER, required: false },
];

const CHARGER_FIELDS: ProductField[] = [
  ...BASE_SYSTEM_FIELDS,
  ...RESEARCH_FIELDS,
  { id: 'max_power', name: '总功率 (W)', type: FieldType.NUMBER, required: false },
];

const EARBUDS_FIELDS: ProductField[] = [
  ...BASE_SYSTEM_FIELDS,
  ...RESEARCH_FIELDS,
  { id: 'battery_life', name: '续航时间(h)', type: FieldType.NUMBER, required: false },
  { id: 'bluetooth_version', name: '蓝牙版本', type: FieldType.SELECT, required: false, options: ['5.0', '5.1', '5.2', '5.3'] },
  { id: 'noise_cancelling', name: '降噪功能', type: FieldType.SELECT, required: false, options: ['主动降噪', '被动降噪', '无'] },
  { id: 'water_resistance', name: '防水等级', type: FieldType.SELECT, required: false, options: ['IPX4', 'IPX5', 'IPX7', 'IP68'] },
];

const SMARTWATCH_FIELDS: ProductField[] = [
  ...BASE_SYSTEM_FIELDS,
  ...RESEARCH_FIELDS,
  { id: 'screen_size', name: '屏幕尺寸(英寸)', type: FieldType.NUMBER, required: false },
  { id: 'compatibility', name: '兼容系统', type: FieldType.TEXT, required: false },
  { id: 'battery_days', name: '续航天数', type: FieldType.NUMBER, required: false },
  { id: 'water_resistance', name: '防水等级', type: FieldType.SELECT, required: false, options: ['30m', '50m', '100m', '200m'] },
];

const LAPTOP_FIELDS: ProductField[] = [
  ...BASE_SYSTEM_FIELDS,
  ...RESEARCH_FIELDS,
  { id: 'cpu_model', name: '处理器型号', type: FieldType.TEXT, required: false },
  { id: 'ram_gb', name: '内存(GB)', type: FieldType.NUMBER, required: false },
  { id: 'storage_gb', name: '存储(GB)', type: FieldType.NUMBER, required: false },
  { id: 'screen_size', name: '屏幕尺寸(英寸)', type: FieldType.NUMBER, required: false },
  { id: 'weight_kg', name: '重量(kg)', type: FieldType.NUMBER, required: false },
];

const PHONE_FIELDS: ProductField[] = [
  ...BASE_SYSTEM_FIELDS,
  ...RESEARCH_FIELDS,
  { id: 'screen_size', name: '屏幕尺寸(英寸)', type: FieldType.NUMBER, required: false },
  { id: 'ram_gb', name: '内存(GB)', type: FieldType.NUMBER, required: false },
  { id: 'storage_gb', name: '存储(GB)', type: FieldType.NUMBER, required: false },
  { id: 'battery_mah', name: '电池容量(mAh)', type: FieldType.NUMBER, required: false },
  { id: 'network_5g', name: '5G网络', type: FieldType.SELECT, required: false, options: ['支持', '不支持'] },
];

export const MOCK_PRODUCTS: ProductData[] = [
  // 移动电源 5 条
  { id: 'm1', period: TODAY, categoryId: 'cat_powerbank', channel: 'Amazon', brand: 'Anker', model: '737 Power Bank (GaNPrime)', price: 199, monthlySales: 4500, rating: 4.8, createdAt: NOW, mainImage: 'https://picsum.photos/seed/m1/400/500', shopName: 'Anker Official', capacity_mah: 24000, max_output: 140, dataReliability: '高 (确凿数据)', sellingPoints: 'PD 3.1 140W双向快充，智能数显屏。' },
  { id: 'm2', period: TODAY, categoryId: 'cat_powerbank', channel: 'Rakuten', brand: '小米', model: '10000mAh 33W 快充版', price: 89, monthlySales: 12000, rating: 4.6, createdAt: NOW - 86400000, mainImage: 'https://picsum.photos/seed/m2/400/500', shopName: '小米旗舰店', capacity_mah: 10000, max_output: 33, sellingPoints: '高性价比，小米生态链。' },
  { id: 'm3', period: TODAY, categoryId: 'cat_powerbank', channel: 'Yahoo Shopping', brand: '罗马仕', model: 'Sense 6+ 20000mAh', price: 129, monthlySales: 8000, rating: 4.5, createdAt: NOW - 172800000, mainImage: 'https://picsum.photos/seed/m3/400/500', shopName: 'Romoss Store', capacity_mah: 20000, max_output: 22, sellingPoints: '大容量，双USB输出。' },
  { id: 'm4', period: TODAY, categoryId: 'cat_powerbank', channel: 'Amazon', brand: '紫米', model: '20号 Pro 25000mAh', price: 369, monthlySales: 3200, rating: 4.9, createdAt: NOW - 259200000, mainImage: 'https://picsum.photos/seed/m4/400/500', shopName: 'ZMI Official', capacity_mah: 25000, max_output: 200, sellingPoints: '专业级，支持笔记本充电。' },
  { id: 'm5', period: TODAY, categoryId: 'cat_powerbank', channel: 'Rakuten', brand: '品胜', model: 'PB-T20 20000mAh', price: 99, monthlySales: 5600, rating: 4.4, createdAt: NOW - 345600000, mainImage: 'https://picsum.photos/seed/m5/400/500', shopName: 'Pisen Direct', capacity_mah: 20000, max_output: 18, sellingPoints: '国民品牌，稳定耐用。' },

  // 充电器 4 条
  { id: 'c1', period: TODAY, categoryId: 'cat_charger', channel: 'Amazon', brand: 'Anker', model: 'GaNPrime 120W 三口', price: 269, monthlySales: 2800, rating: 4.8, createdAt: NOW, mainImage: 'https://picsum.photos/seed/c1/400/500', shopName: 'Anker Official', max_power: 120, sellingPoints: 'GaN氮化镓，三设备同时快充。' },
  { id: 'c2', period: TODAY, categoryId: 'cat_charger', channel: 'Rakuten', brand: '小米', model: '67W 氮化镓套装', price: 149, monthlySales: 6500, rating: 4.7, createdAt: NOW - 86400000, mainImage: 'https://picsum.photos/seed/c2/400/500', shopName: '小米旗舰店', max_power: 67, sellingPoints: '套装含线，性价比高。' },
  { id: 'c3', period: TODAY, categoryId: 'cat_charger', channel: 'Yahoo Shopping', brand: '绿联', model: '100W 四口氮化镓', price: 199, monthlySales: 4200, rating: 4.6, createdAt: NOW - 172800000, mainImage: 'https://picsum.photos/seed/c3/400/500', shopName: 'UGREEN Store', max_power: 100, sellingPoints: '四口输出，多设备办公。' },
  { id: 'c4', period: TODAY, categoryId: 'cat_charger', channel: 'Amazon', brand: 'Baseus', model: '65W 氮化镓', price: 89, monthlySales: 9200, rating: 4.5, createdAt: NOW - 259200000, mainImage: 'https://picsum.photos/seed/c4/400/500', shopName: 'Baseus Official', max_power: 65, sellingPoints: '轻薄便携，PD快充。' },

  // 蓝牙耳机 4 条
  { id: 'e1', period: TODAY, categoryId: 'cat_earbuds', channel: 'Amazon', brand: 'Apple', model: 'AirPods Pro 2', price: 1899, monthlySales: 15000, rating: 4.9, createdAt: NOW, mainImage: 'https://picsum.photos/seed/e1/400/500', shopName: 'Apple Store', battery_life: 6, bluetooth_version: '5.3', noise_cancelling: '主动降噪', water_resistance: 'IPX4', sellingPoints: '空间音频，自适应降噪。' },
  { id: 'e2', period: TODAY, categoryId: 'cat_earbuds', channel: 'Rakuten', brand: '索尼', model: 'WF-1000XM5', price: 1499, monthlySales: 6200, rating: 4.8, createdAt: NOW - 86400000, mainImage: 'https://picsum.photos/seed/e2/400/500', shopName: 'Sony Direct', battery_life: 8, bluetooth_version: '5.3', noise_cancelling: '主动降噪', water_resistance: 'IPX4', sellingPoints: '业界顶级降噪，LDAC高清。' },
  { id: 'e3', period: TODAY, categoryId: 'cat_earbuds', channel: 'Yahoo Shopping', brand: '华为', model: 'FreeBuds Pro 3', price: 899, monthlySales: 9800, rating: 4.7, createdAt: NOW - 172800000, mainImage: 'https://picsum.photos/seed/e3/400/500', shopName: 'Huawei VMall', battery_life: 7, bluetooth_version: '5.3', noise_cancelling: '主动降噪', water_resistance: 'IPX4', sellingPoints: '超感知降噪，麒麟A2芯片。' },
  { id: 'e4', period: TODAY, categoryId: 'cat_earbuds', channel: 'Amazon', brand: '小米', model: 'Buds 4 Pro', price: 699, monthlySales: 11000, rating: 4.6, createdAt: NOW - 259200000, mainImage: 'https://picsum.photos/seed/e4/400/500', shopName: 'Xiaomi Global', battery_life: 9, bluetooth_version: '5.3', noise_cancelling: '主动降噪', water_resistance: 'IPX4', sellingPoints: '48dB降噪，高性价比。' },

  // 智能手表 4 条
  { id: 's1', period: TODAY, categoryId: 'cat_smartwatch', channel: 'Amazon', brand: 'Apple', model: 'Watch Ultra 2', price: 6499, monthlySales: 4200, rating: 4.9, createdAt: NOW, mainImage: 'https://picsum.photos/seed/s1/400/500', shopName: 'Apple Store', screen_size: 1.92, battery_days: 2, water_resistance: '100m', sellingPoints: '钛金属表壳，双频GPS，潜水级。' },
  { id: 's2', period: TODAY, categoryId: 'cat_smartwatch', channel: 'Rakuten', brand: '华为', model: 'Watch GT 4', price: 1488, monthlySales: 8500, rating: 4.8, createdAt: NOW - 86400000, mainImage: 'https://picsum.photos/seed/s2/400/500', shopName: 'Huawei VMall', screen_size: 1.43, battery_days: 14, water_resistance: '50m', sellingPoints: '超长续航，健康管理全面。' },
  { id: 's3', period: TODAY, categoryId: 'cat_smartwatch', channel: 'Yahoo Shopping', brand: '小米', model: 'Watch S3', price: 999, monthlySales: 12000, rating: 4.6, createdAt: NOW - 172800000, mainImage: 'https://picsum.photos/seed/s3/400/500', shopName: 'Xiaomi Global', screen_size: 1.43, battery_days: 15, water_resistance: '50m', sellingPoints: '澎湃OS，百变表圈。' },
  { id: 's4', period: TODAY, categoryId: 'cat_smartwatch', channel: 'Amazon', brand: 'OPPO', model: 'Watch 4 Pro', price: 2299, monthlySales: 3600, rating: 4.7, createdAt: NOW - 259200000, mainImage: 'https://picsum.photos/seed/s4/400/500', shopName: 'OPPO Store', screen_size: 1.91, battery_days: 5, water_resistance: '50m', sellingPoints: '骁龙W5，eSIM独立通话。' },

  // 笔记本电脑 4 条
  { id: 'l1', period: TODAY, categoryId: 'cat_laptop', channel: 'Amazon', brand: 'Apple', model: 'MacBook Pro 14 M3 Pro', price: 14999, monthlySales: 2800, rating: 4.9, createdAt: NOW, mainImage: 'https://picsum.photos/seed/l1/400/500', shopName: 'Apple Store', cpu_model: 'M3 Pro', ram_gb: 18, storage_gb: 512, screen_size: 14.2, weight_kg: 1.55, sellingPoints: '专业创作，ProMotion屏幕。' },
  { id: 'l2', period: TODAY, categoryId: 'cat_laptop', channel: 'Rakuten', brand: '联想', model: 'ThinkPad X1 Carbon', price: 9999, monthlySales: 4500, rating: 4.7, createdAt: NOW - 86400000, mainImage: 'https://picsum.photos/seed/l2/400/500', shopName: 'Lenovo Direct', cpu_model: 'i7-1365U', ram_gb: 16, storage_gb: 512, screen_size: 14, weight_kg: 1.12, sellingPoints: '商务标杆，军工级耐用。' },
  { id: 'l3', period: TODAY, categoryId: 'cat_laptop', channel: 'Yahoo Shopping', brand: '华为', model: 'MateBook X Pro', price: 8999, monthlySales: 6200, rating: 4.8, createdAt: NOW - 172800000, mainImage: 'https://picsum.photos/seed/l3/400/500', shopName: 'Huawei VMall', cpu_model: 'i7-1360P', ram_gb: 16, storage_gb: 512, screen_size: 14.2, weight_kg: 1.26, sellingPoints: '3.1K触控屏，超级终端。' },
  { id: 'l4', period: TODAY, categoryId: 'cat_laptop', channel: 'Amazon', brand: '小米', model: 'RedmiBook Pro 15', price: 4999, monthlySales: 9500, rating: 4.5, createdAt: NOW - 259200000, mainImage: 'https://picsum.photos/seed/l4/400/500', shopName: 'Xiaomi Global', cpu_model: 'i5-13500H', ram_gb: 16, storage_gb: 512, screen_size: 15.6, weight_kg: 1.78, sellingPoints: '3.2K高刷屏，高性价比。' },

  // 智能手机 5 条
  { id: 'p1', period: TODAY, categoryId: 'cat_phone', channel: 'Amazon', brand: 'Apple', model: 'iPhone 15 Pro Max', price: 9999, monthlySales: 22000, rating: 4.9, createdAt: NOW, mainImage: 'https://picsum.photos/seed/p1/400/500', shopName: 'Apple Store', screen_size: 6.7, ram_gb: 8, storage_gb: 256, battery_mah: 4422, network_5g: '支持', sellingPoints: 'A17 Pro，钛金属，动作按钮。' },
  { id: 'p2', period: TODAY, categoryId: 'cat_phone', channel: 'Rakuten', brand: '华为', model: 'Mate 60 Pro+', price: 8999, monthlySales: 18000, rating: 4.8, createdAt: NOW - 86400000, mainImage: 'https://picsum.photos/seed/p2/400/500', shopName: 'Huawei VMall', screen_size: 6.82, ram_gb: 12, storage_gb: 512, battery_mah: 5000, network_5g: '支持', sellingPoints: '麒麟9000s，卫星通信，鸿蒙4。' },
  { id: 'p3', period: TODAY, categoryId: 'cat_phone', channel: 'Yahoo Shopping', brand: '小米', model: '14 Ultra', price: 5999, monthlySales: 12000, rating: 4.7, createdAt: NOW - 172800000, mainImage: 'https://picsum.photos/seed/p3/400/500', shopName: 'Xiaomi Global', screen_size: 6.73, ram_gb: 16, storage_gb: 512, battery_mah: 5000, network_5g: '支持', sellingPoints: '徕卡Summilux，可变光圈。' },
  { id: 'p4', period: TODAY, categoryId: 'cat_phone', channel: 'Amazon', brand: 'OPPO', model: 'Find X7 Ultra', price: 5999, monthlySales: 8500, rating: 4.8, createdAt: NOW - 259200000, mainImage: 'https://picsum.photos/seed/p4/400/500', shopName: 'OPPO Store', screen_size: 6.82, ram_gb: 16, storage_gb: 512, battery_mah: 5000, network_5g: '支持', sellingPoints: '双潜望长焦，哈苏影像。' },
  { id: 'p5', period: TODAY, categoryId: 'cat_phone', channel: 'Rakuten', brand: 'vivo', model: 'X100 Pro', price: 4999, monthlySales: 14000, rating: 4.7, createdAt: NOW - 345600000, mainImage: 'https://picsum.photos/seed/p5/400/500', shopName: 'vivo Direct', screen_size: 6.78, ram_gb: 16, storage_gb: 512, battery_mah: 5400, network_5g: '支持', sellingPoints: '天玑9300，蔡司APO长焦。' },
];

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'cat_powerbank', name: '充电宝', fields: POWERBANK_FIELDS },
  { id: 'cat_charger', name: '充电器/适配器', fields: CHARGER_FIELDS },
  { id: 'cat_earbuds', name: '蓝牙耳机', fields: EARBUDS_FIELDS },
  { id: 'cat_smartwatch', name: '智能手表', fields: SMARTWATCH_FIELDS },
  { id: 'cat_laptop', name: '笔记本电脑', fields: LAPTOP_FIELDS },
  { id: 'cat_phone', name: '智能手机', fields: PHONE_FIELDS },
];
